#!/usr/bin/env bash
# update-api-base.sh — sets the backend URL for the whole project
# Usage: bash termux-setup/update-api-base.sh https://your-device.ts.net
#        (or run with no args to read from config/.env TAILSCALE_URL)

SITE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_FILE="$SITE_DIR/config/.env"
[ -f "$ENV_FILE" ] && . "$ENV_FILE"

NEW_URL="${1:-${TAILSCALE_URL:-${BACKEND_URL:-}}}"
NEW_URL="${NEW_URL%/}"   # strip trailing slash

if [ -z "$NEW_URL" ]; then
  echo "Usage: bash termux-setup/update-api-base.sh https://your-device.ts.net"
  exit 1
fi

echo "Setting API base → $NEW_URL"

# 1. Write www/config.js — loaded by index.html before any scripts
mkdir -p "$SITE_DIR/www"
cat > "$SITE_DIR/www/config.js" << JS
// Auto-generated by update-api-base.sh — do not edit manually
window.INNERFLECT_API_BASE = '$NEW_URL';
JS
echo "  ✓ www/config.js"

# 1b. Write public/config.js — used by Vite dev server
mkdir -p "$SITE_DIR/public"
cat > "$SITE_DIR/public/config.js" << JS
// Auto-generated by update-api-base.sh — do not edit manually
window.INNERFLECT_API_BASE = '$NEW_URL';
JS
echo "  ✓ public/config.js"

# 2. Save to config/.env
grep -q "^TAILSCALE_URL" "$ENV_FILE" 2>/dev/null \
  && sed -i "s|^TAILSCALE_URL=.*|TAILSCALE_URL=$NEW_URL|" "$ENV_FILE" \
  || echo "TAILSCALE_URL=$NEW_URL" >> "$ENV_FILE"
grep -q "^BACKEND_URL" "$ENV_FILE" 2>/dev/null \
  && sed -i "s|^BACKEND_URL=.*|BACKEND_URL=$NEW_URL|" "$ENV_FILE" \
  || echo "BACKEND_URL=$NEW_URL" >> "$ENV_FILE"
echo "  ✓ config/.env"

echo ""
echo "Done. Restart Innerflect to apply: bash $SITE_DIR/start.sh"
